version: '3.9'

services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    env_file:
      - ./env/kafka.env

  akhq:
      image: tchiotludo/akhq:latest
      container_name: akhq
      ports:
        - 8080:8080
      volumes:
        - ./volumes/akhq/application.yml:/app/application.yml:ro
      environment:
        - AKHQ_CONFIGURATION_FILE=/app/application.yml
      depends_on:
        - broker

  influxdb:
      image: influxdb:2.7
      container_name: influxdb
      ports:
        - 8086:8086
      env_file:
        ./env/influxdb.env
      volumes:
        - ./volumes/influxdb:/var/lib/influxdb2

  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    depends_on:
      - broker
      - influxdb
    entrypoint: ["/bin/sh", "-c", "until nc -z broker 29092; do echo waiting for kafka; sleep 2; done; telegraf"]
    volumes:
      - ./volumes/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  influxdb:
  telegraf:
  akhq: