version: '3.9'

services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  akhq:
      image: tchiotludo/akhq:latest
      container_name: akhq
      ports:
        - 8080:8080
      environment:
        AKHQ_CONFIGURATION: |
          akhq:
            connections:
              docker-kafka:
                properties:
                  bootstrap.servers: "broker:29092"
      depends_on:
        - broker

  influxdb:
      image: influxdb:2.7
      container_name: influxdb
      ports:
        - 8086:8086
      environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: admin
        DOCKER_INFLUXDB_INIT_PASSWORD: admin123
        DOCKER_INFLUXDB_INIT_ORG: kafka-org
        DOCKER_INFLUXDB_INIT_BUCKET: kafka-metrics
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: apiv3_guUH_7hbURvrEWliiXI3E_A11VZkWtGPC3S5Jukv0--2iiwU9KZn4ofRIiypT6DWEL0ib3Jkrb6hjX0eTrD8VQ
      volumes:
        - influxdb-data:/var/lib/influxdb2

  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    depends_on:
      - broker
      - influxdb
    entrypoint: ["/bin/sh", "-c", "until nc -z broker 29092; do echo waiting for kafka; sleep 2; done; telegraf"]
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  influxdb-data: